FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y software-properties-common sshpass python3 python3-pip openssh-client && \
    apt-add-repository --yes --update ppa:ansible/ansible && \
    apt-get install -y ansible && \
    apt-get clean

# Create ansible directory
RUN mkdir -p /ansible
WORKDIR /ansible
CMD ["/bin/bash"]
